
NOTE: This document is meant as a starting point for comprehensively documenting the _"auto-skip"_ feature. Feel free to submit pull requests with any additional changes you may have. If a dev who maintains official Plex Media Server source code sees this, feel free to use it or submit your input.

Throughout this document the feature of interest will be referred to as _"auto-skip"_.
This feature shall support skipping both intros and outros of TV shows.

It should be assumed that not all TV shows have intros or outros.
Furthermore, TV shows that do have intros or outros do not follow the same convention for where an intro or outro is located within a video or TV series.

== Video Intro and Outro Conventions

Many TV shows begin their intro and outro credits at the same time in every episode, but many do not.
Furthermore, many TV shows' intro and outro credits span the same amount of time throughout a season or series, but many do not.
TV shows aside, there are other use cases that may need auto-skip timing to be customizable.
Such a case may be a home video recorded decades ago on https://en.wikipedia.org/wiki/VHS[VHS] that has been digitized, but has poor quality content that is not worth watching or blank spans of time between the recordings.

.Video Use Cases
[plantuml,align="center"]
----
include::autoskip_feature_use_case_diagram.puml[]
----

=== Intro starts at 00:00

.Intro starts at 00:00
[plantuml,align="center"]
----
include::intro_starts_at_00_00.puml[]
----

=== Intro starts after 00:00

.Intro starts after 00:00
[plantuml,align="center"]
----
include::intro_starts_after_00_00.puml[]
----

=== Outro starts at end with previews

.Outro starts at end with previews
[plantuml,align="center"]
----
include::outro_starts_at_end_with_previews.puml[]
----

=== Outro starts at end without previews

.Outro starts at end without previews
[plantuml,align="center"]
----
include::outro_starts_at_end_without_previews.puml[]
----

[#skippable-content-in-middle]
=== Skippable content in middle

.Skippable content in middle
[plantuml,align="center"]
----
include::skippable_content_in_middle.puml[]
----

== Client/Server Interaction

The _"auto-skip"_ feature will require interaction between client and server.
There are several supported clients, some of which may not support the ability to configure preferences, which may make configuring this feature impossible for those clients.

.Client/Server Interaction Use Cases
[plantuml,align="center"]
----
include::skip_intro_use_case_diagram.puml[]
----

When a user chooses to enable the _"auto-skip"_ feature, they do so through their client.

.Enabling auto-skip feature
[plantuml,align="center"]
----
include::enabling_autoskip_feature_activity_diagram.puml[]
----

When the Plex Media Server starts to stream a video and support the _"auto-skip"_ feature there are some things it needs to take into account.

. Does the current client want to auto-skip content at all?
. Does the current client want to be prompted to auto-skip content?

.Serving video stream
[plantuml,align="center"]
----
include::serving_video_activity_diagram.puml[]
----

== Metadata

In order for Plex Media Server to know when to skip in videos it needs data to tell it when to skip and how long to skip.
There are two methods this data can be acquired: _manually_ and _automatically_.

=== Manual metadata

This method is fairly straight forward.
The user controlling the Plex Media Server can specify a configuration text file in the folder containing any videos that have content they want to _"auto-skip"_.

[#example-config-file]
==== Example config text file

Below is simply an example of what a config text file _could_ look like.

----
// An example config text file for auto-skip feature.
// Comments are supported in this example via double '/' character.
my_awesome_home_video.mkv
    @04:12,+00:11 // black screen
    @08:27,+00:05 // black screen
    @01:03:49,+00:45 // really crappy quality not worth watching
Your Favorite TV Show/Season 1/S01E01-pilot.mp4
Your Favorite TV Show/Season 1/S01E02-example-title.mp4
Your Favorite TV Show/Season 1/S01E03-example-title.mp4
Your Favorite TV Show/Season 1/S01E04-example-title.mp4
Your Favorite TV Show/Season 1/S01E05-example-title.mp4
Your Favorite TV Show/Season 1/S01E06-example-title.mp4
Your Favorite TV Show/Season 1/S01E07-example-title.mp4
Your Favorite TV Show/Season 1/S01E08-example-title.mp4
    @00:00,+00:30
// Globs are supported in this example.
Your Favorite TV Show/Season 2/S02E*.mp4
    @00:00,+00:30
----

=== Automatic metadata

This method requires more work than the manual method from the developers perspective.
This method may also be more difficult to implement in use cases like <<skippable-content-in-middle,Skippable content in middle>>.

See link:https://github.com/Hellowlol/bw_plex[bw_plex] for a Github project that automatically determines potential skippable content.
