@startuml "Video Intro/Outro Possibilities"
left to right direction

note as GeneralNote
    All these scenarios can be generalized
    by a feature that supports skipping multiple
    durations within a video.
end note

:Video:

(Intro starts at 0:00)
(Intro starts after 0:00)
(Outro starts at end\nwithout previews)
(Outro starts at end\nwith previews)
(Skippable content\nin middle)

:Video: --> (Intro starts at 0:00)
:Video: --> (Intro starts after 0:00)
:Video: --> (Outro starts at end\nwithout previews)
:Video: --> (Outro starts at end\nwith previews)
:Video: --> (Skippable content\nin middle)

@enduml